[build]
target = "avr-none"

[target.avr-none]
rustflags = ["-C", "target-cpu=atmega328p", "-C", "link-arg=-Tavr-atmega328p_linker.ld"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude"

[unstable]
build-std = ["core"]
